// Mocks generated by Mockito 5.4.4 from annotations
// in magicview/test/bloc/get_users/get_user_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:magicview/adapter/sharePreferencesAdapter.dart' as _i6;
import 'package:magicview/reposistories/remote/favorite_repositoy_impl.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FavoriteRespositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoriteRespositoryImpl extends _i1.Mock
    implements _i2.FavoriteRespositoryImpl {
  MockFavoriteRespositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> login({
    required String? url,
    required String? endPoint,
    Map<String, String>? headers = const {
      r'Content-type': r'application/json',
      r'Accept': r'application/json',
    },
    required Map<String, String>? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #url: url,
            #endPoint: endPoint,
            #headers: headers,
            #body: body,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> addUser({
    required String? url,
    required String? endPoint,
    Map<String, String>? headers = const {
      r'Content-type': r'application/json',
      r'Accept': r'application/json',
    },
    required Map<String, String>? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addUser,
          [],
          {
            #url: url,
            #endPoint: endPoint,
            #headers: headers,
            #body: body,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<String> upload({
    required String? url,
    required String? endPoint,
    required Map<String, String>? headers,
    required _i4.File? fileName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upload,
          [],
          {
            #url: url,
            #endPoint: endPoint,
            #headers: headers,
            #fileName: fileName,
          },
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #upload,
            [],
            {
              #url: url,
              #endPoint: endPoint,
              #headers: headers,
              #fileName: fileName,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> post({
    required String? url,
    required String? endPoint,
    required Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [],
          {
            #url: url,
            #endPoint: endPoint,
            #headers: headers,
          },
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #post,
            [],
            {
              #url: url,
              #endPoint: endPoint,
              #headers: headers,
            },
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<Map<String, dynamic>> getUser({
    required String? url,
    required String? endPoint,
    Map<String, String>? queryParament = const {},
    required Map<String, String>? headers,
    Map<String, String>? body = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [],
          {
            #url: url,
            #endPoint: endPoint,
            #queryParament: queryParament,
            #headers: headers,
            #body: body,
          },
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<dynamic>> getList({
    required String? url,
    required String? endPoint,
    Map<String, String>? queryParament = const {},
    required Map<String, String>? headers,
    Map<String, String>? body = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getList,
          [],
          {
            #url: url,
            #endPoint: endPoint,
            #queryParament: queryParament,
            #headers: headers,
            #body: body,
          },
        ),
        returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i3.Future<List<dynamic>>);
}

/// A class which mocks [SharePrefrencesAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharePrefrencesAdapter extends _i1.Mock
    implements _i6.SharePrefrencesAdapter {
  MockSharePrefrencesAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> get(String? key) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> set(
    String? key,
    Map<String, dynamic>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            key,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> saveToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [token],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addCountFavorite(
    String? key,
    int? count,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCountFavorite,
          [
            key,
            count,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getCountFavorite(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getCountFavorite,
          [key],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
